<a href="https://colab.research.google.com/github/Ayaan-tech/my-projects/blob/main/Machine_learning_basics_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as ps


In [21]:
import numpy  as np

LIST VS NUMPY - TIME TAKEN

In [14]:
from time import process_time

Time taken by a List

In [15]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0013837910000003006


Time Taken By a numpy Array


In [18]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.00031735499999996364


In [44]:
from __future__ import print_function
#Creating a 1-D array and 2-D array
a = np.array([1 , 2 , 3 , 4,(1)])
print(a)


b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

# Creating a numpy matrix with all  zeroes

x = np.zeros((2,2))
print(x)
 # Creating a matrix with ones

y = np.ones((3,3))
print(y)

# Creating a numpy matrix of a particular value

z= np.full((1,1),5)
print(z)

# Creating an identity matrix
w = np.eye(5)
print(w)

# Creating a matrix with random values
d= np.random.random((3,4))
print(d)

# Random values with a particular range
e = np.random.randint(10,100,(3,6))
print(e)

# Creating an evenly spaced array
q = np.linspace(10,3,5)
print(q)

# Creating array with evenly spaced values --> Specifying the range
u = np.arange(10,30,5)
print(u)

[1 2 3 4 1]
[[1 2 3 4]
 [5 6 7 8]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.90056138 0.42048343 0.07248757 0.1233101 ]
 [0.22498419 0.80246627 0.86761634 0.92773807]
 [0.70696022 0.68834681 0.43736758 0.3671267 ]]
[[24 77 71 97 89 94]
 [44 13 75 77 71 77]
 [43 14 71 54 52 12]]
[10.    8.25  6.5   4.75  3.  ]
[10 15 20 25]
